"""New DB Structure

Revision ID: 54d1ee5d08f3
Revises: 240ab3d23f77
Create Date: 2024-11-08 13:14:49.078506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d1ee5d08f3'
down_revision: Union[str, None] = '240ab3d23f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_data',
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('currency_id')
    )
    op.create_index(op.f('ix_currency_data_currency_id'), 'currency_data', ['currency_id'], unique=False)
    op.create_table('currency_data_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_currency_data_history_currency_id'), 'currency_data_history', ['currency_id'], unique=False)
    op.drop_index('ix_currencies_history_id', table_name='currencies_history')
    op.drop_index('ix_currencies_history_name', table_name='currencies_history')
    op.drop_table('currencies_history')
    op.add_column('currencies', sa.Column('symbol', sa.String(), nullable=False))
    op.alter_column('currencies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_currencies_name', table_name='currencies')
    op.drop_index('ix_currencies_id', table_name='currencies')
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=True)
    op.create_unique_constraint(None, 'currencies', ['symbol'])
    op.drop_column('currencies', 'price')
    op.drop_column('currencies', 'date')
    op.drop_column('currencies', 'market_cap')
    op.drop_column('currencies', 'price_history')
    op.drop_column('currencies', 'market_cap_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('market_cap_history', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.add_column('currencies', sa.Column('price_history', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.add_column('currencies', sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('currencies', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('currencies', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'currencies', type_='unique')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.create_index('ix_currencies_id', 'currencies', ['id'], unique=False)
    op.create_index('ix_currencies_name', 'currencies', ['name'], unique=False)
    op.alter_column('currencies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('currencies', 'symbol')
    op.create_table('currencies_history',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_history', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('market_cap_history', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='currencies_history_pkey')
    )
    op.create_index('ix_currencies_history_name', 'currencies_history', ['name'], unique=False)
    op.create_index('ix_currencies_history_id', 'currencies_history', ['id'], unique=False)
    op.drop_index(op.f('ix_currency_data_history_currency_id'), table_name='currency_data_history')
    op.drop_table('currency_data_history')
    op.drop_index(op.f('ix_currency_data_currency_id'), table_name='currency_data')
    op.drop_table('currency_data')
    # ### end Alembic commands ###
