name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sanlamamba
          password: dckr_pat_0PSOGQN0ZIy_RGKrig-x3B0ewAo

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./data_flow
          push: true
          tags: |
            sanlamamba/cryptoviz_dataflow:latest
            sanlamamba/cryptoviz_dataflow:${{ github.sha }}
