name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build the image
        run: cd data_flow && docker-compose build

      - name: Tag the image with Git SHA
        run: docker tag sanlamamba/cryptoviz_dataflow:latest sanlamamba/cryptoviz_dataflow:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sanlamamba
          password: dckr_pat_0PSOGQN0ZIy_RGKrig-x3B0ewAo
          # DOCKER_HUB_USERNAME and DOCKER_HUB_PAT

      - name: Push the image
        run: docker push sanlamamba/cryptoviz_dataflow:${{ github.sha }}
